export const GET_PLANETS_EPIC = "GET_PLANETS_EPIC";
export const GET_PLANETS_SUCCEDED = "GET_PLANETS_SUCCEDED";
export const GET_PLANETS_FAILED = "GET_PLANETS_FAILED";
export const GET_PLANETS_READING = "GET_PLANETS_READING";
export const GET_PLANETS_CANCEL = "GET_PLANETS_CANCEL";
