export const GET_PLANETS_AJAX_EPIC = "GET_PLANETS_AJAX_EPIC";
export const GET_PLANETS_AJAX_SUCCEDED = "GET_PLANETS_AJAX_SUCCEDED";
export const GET_PLANETS_AJAX_FAILED = "GET_PLANETS_AJAX_FAILED";
export const GET_PLANETS_AJAX_READING = "GET_PLANETS_AJAX_READING";
export const GET_PLANETS_AJAX_CANCEL = "GET_PLANETS_AJAX_CANCEL";
